GET http://localhost:3001/

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/63ef4f720addf5ae95d9881b

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "REST client is good in testing backend",
  "important": true
}

###
PUT http://localhost:3001/api/notes/63ef4f720addf5ae95d9881b
Content-Type: application/json

{
  "content": "TEST 3",
  "important": true
}

###
DELETE http://localhost:3001/api/notes/63f4998f6bf0b8680ccd46a0
